trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'  # Specify the version compatible with .NET 8.0

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Generate a unique version number based on the date and build ID
      $date = Get-Date -Format "yyyyMMdd"
      $buildId = "$(Build.BuildId)"
      $version = "1.0.$($date).$($buildId)"
      Write-Host "##vso[task.setvariable variable=PackageVersion]$version"
  displayName: 'Generate version number'

- script: dotnet restore
  displayName: 'Restore dependencies'

- script: |
    dotnet build --configuration Release /p:Version=$(PackageVersion)
  displayName: 'Build project with dynamic version'

- script: |
    dotnet test --no-build --verbosity normal
  displayName: 'Run tests'

- script: |
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(PackageVersion)
  displayName: 'Package project with dynamic version'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '4dc3839c-a752-4ff1-94a4-daf1e4b39406/5817c3f7-52ab-48a7-9d23-dc3096ed18a0'
